dubbo:
  scan:
    base-packages: com.alibaba.cloud.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
      host: localhost
#    rmi:
#      name: rmi
#      port: 9090
#      host: localhost
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
