server:
  port: 8000
  servlet:
    context-path: /yuexiang
  #最大工作线程数，默认200, 4核8g内存，线程数经验值800
  #操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。
  tomcat:
    max-threads: 1000
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 100
spring:
  application:
    name: server
  main:
    allow-bean-definition-overriding: true
    #http编码设置
    http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 3
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.20.240:9300
      cluster-name: elasticsearch
      properties:
        path:
          logs: elasticsearch/log
          data: elasticsearch/data
  datasource:
    name: mysqldb
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.56.72.90:3306/yuexiang?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&serverTimezone=Asia/Shanghai
#    username: yuexiang
#    password: Yxiang@123
    #下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.56.72.90:3306/yuexiang?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&serverTimezone=Asia/Shanghai
      username: yuexiang
      password: Yxiang@123
      #初始化连接池大小
      initialSize: 5
      #配置最小空闲数
      minIdle: 5
      #配置最大连接数
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #测试连接
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全
      testWhileIdle: true
      #获取连接时执行检测，建议关闭，影响性能
      testOnBorrow: false
      #归还连接时执行检测，建议关闭，影响性能
      testOnReturn: false
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      poolPreparedStatements: false
      #开启poolPreparedStatements后生效
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注
#      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      aopPatterns: com.enjoy.service.*
      #配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        #IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.21.7
        #IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        #登录名
        login-username: root
        #登录密码
        login-password: root
  aop:
    auto: false
    proxy-target-class: true
mybatis-plus:
#  config-location: mybatis-config.xml
  mapper-locations: mapper/*.xml
  typeAliasesPackage: com.enjoy.entity
#  typeEnumsPackage: com.enjoy.entity.enums
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: true
    # 懒加载
    aggressive-lazy-loading: true
    # NONE：不启用自动映射 PARTIAL：只对非嵌套的 resultMap 进行自动映射 FULL：对所有的 resultMap 都进行自动映射
    auto-mapping-behavior: partial
    # NONE：不做任何处理 (默认值)WARNING：以日志的形式打印相关警告信息 FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: none
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: "null"
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: true
    # 机器 ID 部分(影响雪花ID)
    #    worker-id:
    # 数据标识 ID 部分(影响雪花ID)(workerId 和 datacenterId 一起配置才能重新初始化 Sequence)
  #    datacenter-id:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      #是否开启大写命名，默认不开启
      #capital-mode: false
      #逻辑已删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
      logic-not-delete-value: 0
      #逻辑未删除值,(逻辑删除下有效)
      logic-delete-value: 1
      # IGNORED	忽略判断 NOT_NULL 非NULL判断  NOT_EMPTY 非空判断(只对字符串类型字段,其他类型字段依然为非NULL判断)  DEFAULT	追随全局配置 类似的还有update-strategy、select-strategy等
      insert-strategy: not_null